# Generated by Django 3.1.3 on 2021-01-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='学部名')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='科目名')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('student_number', models.IntegerField(default=0, verbose_name='学籍番号')),
                ('year', models.IntegerField(default=0, verbose_name='学年')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.faculty')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='学科名')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.faculty')),
            ],
        ),
    ]
